
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
#  servlet:
#    context-path: /identity